### ISSUE TITLE
NameError: name 'off' is not defined

### ISSUE THREAD

**Issue by GaoycAI** [FeiLiu36/LLM4MOEA#1]
The funtion '_do' in gpt.py seemly has some bug? In line 82, the code 'try:' under 'while retries > 0:'  seemly can't return the variable 'off'

**Comment by FeiLiu36** [comment]
Return 'off' is outside the While loop, I don't see any conflicts. Could you provide more details on the issue?

**Comment by FeiLiu36** [comment]
Thank you for pointing it out. I have double checked the code and the error may result from the empty ["out_filename"](https://github.com/FeiLiu36/LLM4MOEA/blob/main/MOEAD-LLM/pymoo/operators/crossover/gpt.py). The error is blocked by the try & except, making it hard to identify the detailed bug. 

The code has been updated.
