### ISSUE TITLE
TypeError: get_problem() got an unexpected keyword argument 'n_var'

### ISSUE THREAD

**Issue by nadalalee** [FeiLiu36/LLM4MOEA#2]
Hi! When I tried to minimize a problem other than those in 'problem_interface.py', I encountered the error as shown in the title. It seems that the function 'get_problem(problemname,n_var=dimension)' is not defined in the 'run.py'. I wonder if only the problems in 'problem_interface.py' can be minimized because other problems in 'reproblem.py' seems not be implemented for minimization.

**Comment by FeiLiu36** [comment]
Thank you for pointing it out. Yes, currently it only supports problems in 'problem_interface.py', while other problems could be easily integrated with minor modifications.
