### ISSUE TITLE
pythn run.py报错

### ISSUE THREAD

**Issue by gkrtesia** [FeiLiu36/LLM4MOEA#4]
老师您好，运行python run.py报错了，提示AttributeError: 'NoneType' object has no attribute 'shape'，请问在crossover.py中是否缺少对def _do(self, problem, X, **kwargs):的具体设计？

**Comment by FeiLiu36** [comment]
您好，

1. 请使用代码最新的版本（做了略微修改）
2. 请确保大模型的endpoint， key和模型类型没有问题

如果还有报错，麻烦提供一下运行的指令和terminal的详细输出，谢谢！
