### ISSUE TITLE
OPENAI API Token问题

### ISSUE THREAD

**Issue by communicationDL1** [FeiLiu36/LLM4MOEA#6]
老师您好，我想请教下这边MOEA/D-LLM的run.py功能是进行训练吗？大概需要使用OPENAI GPT3.5 的token数是多少呢？

**Comment by FeiLiu36** [comment]
您好，
> run.py功能是进行训练吗

run.py是直接运行多目标优化，其中把大模型作为算子来产生新的solution, 在run.py里面需要设置你的API endpoint和key, 选择大模型的类型。

> 大概需要使用OPENAI GPT3.5 的token数

一次优化大概需要一千到几千次queries to LLM, 一次 query 大概需要400-600 tokens
